import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safe_area: {
    flex: 1,
    backgroundColor: '#222',
  },
  container: {
    flex: 1,
    backgroundColor: '#222',
  },
  scroll_content: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 15,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#B12A2A',
    paddingVertical: 18,
    paddingHorizontal: 15,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 10,
  },
  menu_icon: {
    padding: 5,
  },
  menu_text: {
    fontSize: 28,
    color: '#fff',
    fontWeight: 'bold',
  },
  header_title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 3,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  title: {
    fontSize: 52,
    fontWeight: 'bold',
    color: '#B12A2A',
    marginTop: 30,
    marginBottom: 10,
    letterSpacing: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 3,
  },
  subtitle: {
    fontSize: 19,
    color: '#eee',
    marginBottom: 40,
    textAlign: 'center',
    lineHeight: 25,
  },
  button: {
    backgroundColor: '#B12A2A',
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  button_disabled: {
    backgroundColor: '#666',
    borderColor: 'rgba(255,255,255,0.1)',
    shadowOpacity: 0.1,
    elevation: 3,
  },
  button_text: {
    color: '#fff',
    fontSize: 19,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  hero_button: {
    width: '85%',
    marginBottom: 20,
    backgroundColor: '#B12A2A',
  },
  product_grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginTop: 40,
    width: '100%',
  },
  product_card: {
    backgroundColor: '#333',
    borderRadius: 15,
    padding: 18,
    alignItems: 'center',
    marginBottom: 25,
    width: '46%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  product_image: {
    width: '100%',
    height: 160,
    borderRadius: 10,
    marginBottom: 12,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  product_name: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 6,
  },
  product_price: {
    fontSize: 18,
    color: '#FFD700',
    fontWeight: 'bold',
  },
  product_detail_container: {
    width: '95%',
    backgroundColor: '#333',
    borderRadius: 20,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  product_detail_image: {
    width: '100%',
    height: 320,
    borderRadius: 15,
    marginBottom: 25,
    resizeMode: 'contain',
    backgroundColor: '#B12A2A',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  product_detail_name: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
    textAlign: 'center',
  },
  product_detail_model: {
    fontSize: 20,
    color: '#ccc',
    marginBottom: 10,
    textAlign: 'center',
  },
  product_detail_price: {
    fontSize: 26,
    color: '#FFD700',
    fontWeight: 'bold',
    marginBottom: 25,
  },
  product_detail_description: {
    fontSize: 17,
    color: '#ccc',
    textAlign: 'center',
    marginBottom: 35,
    lineHeight: 24,
  },
  add_to_cart_button: {
    width: '85%',
    marginBottom: 18,
  },
  back_button: {
    width: '85%',
    backgroundColor: '#444',
    marginBottom: 18,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  screen_title: {
    fontSize: 34,
    fontWeight: 'bold',
    color: '#B12A2A',
    marginBottom: 35,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  empty_cart_text: {
    fontSize: 19,
    color: '#ccc',
    textAlign: 'center',
    marginTop: 60,
    marginBottom: 30,
  },
  current_cart_section: {
    width: '95%',
    backgroundColor: '#333',
    borderRadius: 15,
    padding: 20,
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  section_title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
    textAlign: 'center',
  },
  cart_item: {
    flexDirection: 'row',
    backgroundColor: '#444',
    borderRadius: 10,
    padding: 15,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  cart_item_image: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginRight: 15,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  cart_item_details: {
    flex: 1,
  },
  cart_item_name: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
  },
  cart_item_price: {
    fontSize: 15,
    color: '#ccc',
  },
  cart_item_customization: {
    fontSize: 13,
    color: '#bbb',
  },
  remove_button: {
    backgroundColor: '#D32F2F',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  remove_button_text: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  total_price: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFD700',
    marginTop: 20,
    marginBottom: 15,
    textAlign: 'right',
    width: '100%',
  },
  confirm_purchase_button: {
    width: '90%',
    alignSelf: 'center',
    marginTop: 15,
  },
  order_card: {
    width: '95%',
    backgroundColor: '#333',
    borderRadius: 15,
    padding: 20,
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  order_id: {
    fontSize: 19,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  order_info: {
    fontSize: 15,
    color: '#ccc',
    marginBottom: 5,
  },
  order_status: {
    fontWeight: 'bold',
    color: '#66BB6A',
  },
  order_total: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFD700',
    marginTop: 12,
    textAlign: 'right',
  },
  order_items_container: {
    marginTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#555',
    paddingTop: 15,
  },
  order_item: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  order_item_image: {
    width: 55,
    height: 55,
    borderRadius: 8,
    marginRight: 12,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  order_item_details: {
    flex: 1,
  },
  order_item_name: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#fff',
  },
  order_item_customization: {
    fontSize: 12,
    color: '#bbb',
  },
  order_item_price: {
    fontSize: 13,
    color: '#ccc',
  },
  input: {
    width: '85%',
    backgroundColor: '#444',
    padding: 16,
    borderRadius: 10,
    marginBottom: 18,
    color: '#fff',
    fontSize: 17,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  input_large: {
    width: '85%',
    backgroundColor: '#444',
    padding: 16,
    borderRadius: 10,
    marginBottom: 18,
    color: '#fff',
    fontSize: 17,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    height: 100,
    textAlignVertical: 'top',
  },
  auth_button: {
    width: '85%',
    marginBottom: 18,
  },
  link_text: {
    color: '#FFD700',
    fontSize: 17,
    marginBottom: 25,
    textDecorationLine: 'underline',
  },
  menu_overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  menu_container: {
    width: width * 0.7,
    height: '100%',
    backgroundColor: '#1a1a1a',
    paddingTop: 60,
    paddingHorizontal: 25,
    shadowColor: '#000',
    shadowOffset: { width: 8, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: 20,
  },
  menu_item: {
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  menu_item_text: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  centered_view: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  modal_view: {
    margin: 25,
    backgroundColor: '#333',
    borderRadius: 25,
    padding: 40,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  modal_title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#B12A2A',
    marginBottom: 20,
  },
  modal_text: {
    marginBottom: 25,
    textAlign: 'center',
    color: '#eee',
    fontSize: 19,
    lineHeight: 26,
  },
  success_image: {
    width: 120,
    height: 120,
    marginBottom: 25,
  },
  modal_button: {
    backgroundColor: '#B12A2A',
    marginTop: 15,
    paddingHorizontal: 35,
  },
  preview_container: {
    width: '95%',
    height: 350,
    backgroundColor: '#B12A2A',
    borderRadius: 20,
    marginBottom: 35,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  preview_product_image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  preview_print_image: {
    position: 'absolute',
    resizeMode: 'contain',
  },
  customization_options_container: {
    width: '95%',
    backgroundColor: '#333',
    borderRadius: 15,
    padding: 25,
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  option_title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
    marginTop: 20,
  },
  option_row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginBottom: 15,
  },
  option_button: {
    backgroundColor: '#555',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 25,
    marginRight: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  option_button_selected: {
    backgroundColor: '#B12A2A',
    borderWidth: 2,
    borderColor: '#fff',
  },
  option_button_text: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  color_swatch: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    marginRight: 12,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  color_swatch_selected: {
    borderColor: '#fff',
  },
  quantity_container: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    marginTop: 10,
  },
  quantity_button: {
    backgroundColor: '#B12A2A',
    width: 45,
    height: 45,
    borderRadius: 22.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 12,
  },
  quantity_button_text: {
    fontSize: 22,
    color: '#fff',
    fontWeight: 'bold',
  },
  quantity_text: {
    fontSize: 22,
    color: '#fff',
    fontWeight: 'bold',
    minWidth: 40,
    textAlign: 'center',
  },
  confirm_customization_button: {
    width: '85%',
    marginBottom: 18,
  },
  modify_design_button: {
    width: '85%',
    backgroundColor: '#444',
    marginBottom: 18,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  auth_selection_button: {
    width: '85%',
    marginBottom: 25,
  },
});
